before_script:
    - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.10-bin.zip
    - unzip -q gradle.zip

build:
    script:
        - gradle-2.10/bin/gradle version
        - gradle-2.10/bin/gradle build

