image: java

before_script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes wget unzip
    - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.10-bin.zip
    - unzip -q gradle.zip

build:
    script:
        - java -version
        - gradle-2.10/bin/gradle version
        - gradle-2.10/bin/gradle build

